name = "mlbb-checker-worker"            # Nama project worker kamu
type = "javascript"                     # tipe project, bisa juga "webpack" kalau pakai bundler

account_id = "0e9d4d89e79759674c4b4bf64380fe78"          # Ganti dengan Account ID Cloudflare kamu
workers_dev = true                      # Jika ingin deploy ke workers.dev subdomain (true) atau custom domain (false)
route = ""                             # Kosongkan jika pakai workers_dev = true
zone_id = ""                           # Kosongkan jika pakai workers_dev = true

compatibility_date = "2025-08-08"      # Tanggal kompitabilitas, ganti dengan tanggal hari ini atau terbaru

# Binding KV namespace, harus sudah buat namespace di dashboard CF lalu isi id-nya di sini
kv_namespaces = [
  { binding = "VALID_ACCOUNTS", id = "66403b5781584e0bb879f758fe77e8ff" }
]

# Optional settings, kalau kamu pakai fitur lain bisa ditambah di sini
# log_level = "debug"
